### ISSUE TITLE
Call to undefined method ....

### ISSUE THREAD

**Issue by rxt360** [jonnnnyw/php-phantomjs#70]
I've installed php-phantomjs and now try to get a screenshot saved to local disk on my ubuntu machine. I use the following code for test.php:

    <?php
    require 'autoload.php';
    use JonnyW\PhantomJs\Client;
    $client = Client::getInstance();
    $request = $client->getMessageFactory()->createRequest('https://www.google.com', 'GET');
    $request->setCaptureFile('/tmp/file.jpg');
    $response = $client->getMessageFactory()->createResponse();
    $client->send($request, $response);

* test.php is in the same folder as autoload.php
* createCaptureRequest() returned the following error: Call to undefined method JonnyW\\PhantomJs\\Message\\Factory::createCaptureRequest(); changing the method to createRequest() solved this

I added both missing methods to Request.php
* Call to undefined method JonnyW\\PhantomJs\\Message\\Request::setCaptureFile()
* Call to undefined method JonnyW\\PhantomJs\\Message\\Request::setCaptureDimensions()

Now I get the following error:

    [Mon Oct 05 13:52:03.245145 2015] [:error] [pid 3578] [client 127.0.0.1:39069] PHP Fatal error:  Uncaught exception 'JonnyW\\PhantomJs\\Exception\\InvalidMethodException' with message 'Invalid method provided: HTTPS://WWW.GOOGLE.COM' in /var/www/screenshot/vendor/php-phantomjs/jonnyw/php-phantomjs/src/JonnyW/PhantomJs/Message/Request.php:83
    Stack trace:
    #0 /var/www/screenshot/vendor/php-phantomjs/jonnyw/php-phantomjs/src/JonnyW/PhantomJs/Message/Request.php(63): JonnyW\\PhantomJs\\Message\\Request->setMethod('https://www.goo...')
    #1 /var/www/screenshot/vendor/php-phantomjs/jonnyw/php-phantomjs/src/JonnyW/PhantomJs/Message/Factory.php(53): JonnyW\\PhantomJs\\Message\\Request->__construct('https://www.goo...', 'GET')
    #2 /var/www/screenshot/vendor/php-phantomjs/test.php(11): JonnyW\\PhantomJs\\Message\\Factory->createRequest('https://www.goo...', 'GET')
    #3 {main}
  thrown in /var/www/screenshot/vendor/php-phantomjs/jonnyw/php-phantomjs/src/JonnyW/PhantomJs/Message/Request.php on line 83

I guess something is wrong with my setup. I see you request the following command for debugging:

    var_dump($client->getCommand());

This doesn't work, so I use this:

    var_dump($client);

##### Output:

    object(JonnyW\PhantomJs\Client)#2 (6) {
      ["factory":protected]=>
      object(JonnyW\PhantomJs\Message\Factory)#3 (0) {
      }
      ["phantomJS":protected]=>
      string(13) "bin/phantomjs"
      ["wrapper":protected]=>
      string(518) "
    	var page = require('webpage').create(),
    		response = {},
    		headers = %1$s;
    
    	page.settings.resourceTimeout = %2$s;
    	page.onResourceTimeout = function(e) {
    		response 		= e;
    		response.status = e.errorCode;
    	};
    
    	page.onResourceReceived = function (r) {
    		if(!response.status) response = r;
    	};
    
    	page.customHeaders = headers ? headers : {};
    
    	page.open('%3$s', '%4$s', '%5$s', function(status) {
    
    		if(status === 'success') {
    			%6$s
    		}
    
    		console.log(JSON.stringify(response, undefined, 4));
    		phantom.exit();
    	});"
      ["captureCmd":protected]=>
      string(144) "
    			page.render('%1$s');
    
    			response.content = page.evaluate(function () {
    				return document.getElementsByTagName('html')[0].innerHTML
    			});"
      ["openCmd":protected]=>
      string(119) "
    			response.content = page.evaluate(function () {
    				return document.getElementsByTagName('html')[0].innerHTML
    			});"
      ["timeout"]=>
      int(5000)
    }

What is wrong here and how can I get things working normally?

**Comment by rxt360** [comment]
I "solved" this problem by calling PhantomJS directly from the shell.
